[package]
name = "leonard-os"
version = "0.0.0"
authors = ["Gabriel Conrado <gabaconrado@gmail.com>", "Pedro <pedrosmv@gmail.com"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
rlibc = "1.0.0"
<<<<<<< Updated upstream
=======
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
>>>>>>> Stashed changes
